baseURL = 'http://jdiasn.github.io/'
languageCode = 'en-us'
title = 'J.Dias'
#theme = 'ananke'
theme = 'hugo-theme-massively'

googleanalytics = ""
disqusShortname = ""
#disableKinds = ["taxonomy", "taxonomyTerm", "section"]


#[params]
  # set below parameter to define a favicon
#  favicon = "favicon.ico"
  # set to change date format
#  dateFormat = "2.1.2006"
 # backgroundPath = "images/bg.jpg"

# Below parameters can be set to override default post settings
#[params.posts]
#  folderName = "post"
#  pageSize = "2"
#  featuredPost = "true"
#  paginationPages = 6
#  showFirstLast = false
 
[languages]
[languages.en]
  languageName = "English"
  #title = ""
#[languages.es]
#  languageName = "Español"
#  title = "Massively - Versión Español"
#[languages.fr]
#  languageName = "Français"
#  title = "Massively - Version Française"

