#!/bin/bash
OLD1="<pre><code>"
OLD2="</code></pre>"

NEW=" "

echo "Replacing ...."

DPATH="$HOME/projects/mySite/output/*.html"

for f in $DPATH
do
#  echo $f
  sed -i "s/$OLD1/$NEW/g" "$f" 
done

for f in $DPATH
do
#  echo $f
  sed -i "s#$OLD2#$NEW#g" "$f" 
done

DPATH="$HOME/projects/mySite/output/category/*.html"

for f in $DPATH
do
#  echo $f
  sed -i "s/$OLD1/$NEW/g" "$f" 
done

for f in $DPATH
do
#  echo $f
  sed -i "s#$OLD2#$NEW#g" "$f" 
done

cp album.html ./output/pages

echo "Done"
